### PR TITLE
[TASK] Improvements

### PR DESCRIPTION
**Pull request by simkea**

### CODE REVIEW

**Comment by gaiterjones** [comment]
Did the module work for you, I still get a 404 error on 1.9.2.2.

**Comment by simkea** [comment]
Where exactly does the problem occur? URL?
br

**Comment by simkea** [comment]
Oh i see the problem... in my repo exists the IndexController.php
i see in your repo, you have renamed and moved to PrintController.php

**Comment by simkea** [comment]
O.k. ---> forget my pull request... i can see your module has an conflict with an other module in my shop.
There are duplicated rewrites for:
         Blocks:
         adminhtml/sales_order_grid (Magik_Magikfees_Block_Adminhtml_Sales_Order_Grid | Dhl_Intraship_Block_Adminhtml_Sales_Order_Grid)

i will use the fork with my changes in my project...

**Comment by simkea** [comment]
i am confuse... sorry thats not your module :)

**Comment by simkea** [comment]
can i have push right for branch master-simkea plz?!

**Pull request closed without merging**
